parameters:
    studenteninternet_fsnl.class.client: 'Studenteninternet\Fsnl\Client\Client'
    studenteninternet_fsnl.class.configuration: 'Studenteninternet\Fsnl\Client\Configuration\Configuration'
    studenteninternet_fsnl.class.logger: 'Studenteninternet\FsnlBundle\Logger\StudenteninternetFsnlLogger'

services:
    daften.form.subscriber.address:
        class: Daften\Bundle\AddressingBundle\Form\EventListener\AddressEmbeddableTypeSubscriber
        arguments:
          - '@form.factory'
          - '@commerceguys.addressing.country.country_repository'
          - '@commerceguys.addressing.address_format.address_format_repository'
          - '@commerceguys.addressing.subdivision.subdivision_repository'

    daften.form.type.address:
        class: Daften\Bundle\AddressingBundle\Form\Type\AddressEmbeddableType
        arguments:
            -  '@daften.form.subscriber.address'
        public: false
        tags:
            - form.type

    daften.form.type.address_autocomplete_gmaps:
        class: Daften\Bundle\AddressingBundle\Form\Type\AddressEmbeddableGmapsAutocompleteType
        arguments:
            - '@daften.service.gmaps_autocomplete_service'
        public: false
        tags:
            - form.type

    daften.service.gmaps_autocomplete_service:
        class: Daften\Bundle\AddressingBundle\Service\GmapsAutocompleteService
        arguments:
            $countryRepository: '@commerceguys.addressing.country.country_repository'
            $addressFormatRepository: '@commerceguys.addressing.address_format.address_format_repository'
            $subdivisionRepository: '@commerceguys.addressing.subdivision.subdivision_repository'
            $gmapsApiKey: '%env(string:GMAPS_API_KEY)%'
            $requestStack: '@request_stack'

    commerceguys.addressing.country.country_repository:
        class: 'CommerceGuys\Addressing\Country\CountryRepository'

    commerceguys.addressing.address_format.address_format_repository:
        class: 'CommerceGuys\Addressing\AddressFormat\AddressFormatRepository'

    commerceguys.addressing.subdivision.subdivision_repository:
        class: 'CommerceGuys\Addressing\Subdivision\SubdivisionRepository'
