version: "2"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    issue_override:
      severity: minor

exclude_patterns:
- ".github"
- "**/vendor/**/*"
- "tests/"
